[build]
builder = "nixpacks"

[deploy]
startCommand = "cd back-end && npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
PORT = "3001"
